 export const COLORS = {
     head: {
         yellow: "results col-12 text-end bg-warning",
         darkblue: "results col-12 text-end bg-primary",
         white: "results col-12 text-end bg-light",
         green: "results col-12 text-end bg-success",
         red: "results col-12 text-end bg-danger",
         darkgrey: "results col-12 text-end bg-secondary",
     },
     body: {
         rowyellow: "bg-warning",
         colyellow: "col-3  d-flex justify-content-center align-items-center bg-warning",
         coloperatorsyellow: "col-6 d-flex justify-content-center align-items-center bg-warning ",
         buttonyellow: "btn btn-warning btn-lg btn-block modifiybutton789461",
         colorsettingsbodyyellow: "col-12  d-flex justify-content-center align-items-center bg-warning",
         rowdarkblue: "bg-primary",
         coldarkblue: "col-3  d-flex justify-content-center align-items-center bg-primary",
         coloperatorsdarkblue: "col-6 d-flex justify-content-center align-items-center bg-primary ",
         buttondarkblue: "btn btn-primary btn-lg btn-block modifiybutton789461",
         colorsettingsbodydarkblue: "col-12  d-flex justify-content-center align-items-center bg-primary",
         rowblack: "bg-dark",
         colblack: "col-3  d-flex justify-content-center align-items-center bg-dark",
         coloperatorsblack: "col-6 d-flex justify-content-center align-items-center bg-dark ",
         buttonblack: "btn btn-dark btn-lg btn-block modifiybutton789461",
         colorsettingsbodyblack: "col-12  d-flex justify-content-center align-items-center bg-dark",
         rowgreen: "bg-success",
         colgreen: "col-3  d-flex justify-content-center align-items-center bg-success",
         coloperatorsgreen: "col-6 d-flex justify-content-center align-items-center bg-success ",
         buttongreen: "btn btn-success btn-lg btn-block modifiybutton789461",
         colorsettingsbodygreen: "col-12  d-flex justify-content-center align-items-center bg-success",
         rowred: "bg-danger",
         colred: "col-3  d-flex justify-content-center align-items-center bg-danger",
         coloperatorsred: "col-6 d-flex justify-content-center align-items-center bg-danger ",
         buttonred: "btn btn-danger btn-lg btn-block modifiybutton789461",
         colorsettingsbodyred: "col-12  d-flex justify-content-center align-items-center bg-danger",
         rowdarkgrey: "bg-secondary",
         coldarkgrey: "col-3  d-flex justify-content-center align-items-center bg-secondary",
         coloperatorsdarkgrey: "col-6 d-flex justify-content-center align-items-center bg-secondary ",
         buttondarkgrey: "btn btn-secondary btn-lg btn-block modifiybutton789461",
         colorsettingsbodydarkgrey: "col-12  d-flex justify-content-center align-items-center bg-secondary",

     }


 }